### ISSUE TITLE
No getter method to get Blob Client Object and class can not be extended as it is declared as final

### ISSUE THREAD

**Issue by bsomeshwer** [matthewbdaly/laravel-azure-storage#25]
Hi,

I'm using this package in our projects and I'm facing an issue when I'm trying to get the Blob client. Actually, 
I'm unable to get Blob Client object because it is private property. For this, we need getter method called "getClass()" in AzureBlobStorageAdapter class.

Even I can not extend this class as it is declared as final. 

I need below things from your end: 

1. Either you can add getter method to get BlobClient in AzureBlobStorageAdapter class.
or
2. You can make the class as normal class by removing "final" so that I can extend the class.

Out of curiosity I just wanted to ask you that is there any reason behind declaring that class as "final" ?

`Accessing Blob Client is required for me to get Meta data of the file stored in Blob.`

Note: If you want me to submit pull request for this - I can do that.

Thanks

**Comment by matthewbdaly** [comment]
There's a strong case for making *every* class final by default. I refer you to [this blog post](https://ocramius.github.io/blog/when-to-declare-classes-final/) for more details, but essentially, you should always declare a class as final unless it's specifically intended to be extensible. Making it final clearly communicates that the class is not intended to be extended, and avoids a long chain of inheritance. If you need to amend the behaviour of the class, it's often better to do so through composition rather than inheritance, such as writing a decorator to wrap a class.

If you want to submit a pull request to add a getter for the blob client then I am in principle happy to pull that in, though.

**Comment by bsomeshwer** [comment]
My intention behind extending the class is only to add getter method to that Driver class so that I can be able to get BlobClient Object which is actually declared as private. 

So, I'll try to add getter method from my side and if that works I'll send you PR.

**Comment by matthewbdaly** [comment]
What metadata are you after? The File storage API in Laravel has methods to get certain metadata and if those aren't working with this adapter maybe it would make more sense to see if we can resolve that.

**Comment by bsomeshwer** [comment]
Yes, you are right! but unfortunately Laravel methods of File storage API are not returning complete Meta Data information.

In my case I'm adding some custom meta data to a file before uploading/storing it into the Blob Storage. I want to retrieve the same meta data information during file download in the application.

**Comment by matthewbdaly** [comment]
This should now be resolved via the referenced pull request. You can now get the client directly from the container.
