### ISSUE TITLE
The provided account key '' is not a valid base64 string

### ISSUE THREAD

**Issue by brpetrov** [matthewbdaly/laravel-azure-storage#31]
Hi there, I believe I managed to set up the package by downgrading guzzle ...etc. I can see the uploaded files in the Azure blob, but when I try to upload files from Laravel to the Blob I get a 500 (Internal Server Error). The message is saying:
 "The provided account key '' is not a valid base64 string. It has to pass the check 'base64_decode(<user_account_key>, true)'."

I am using this format for the drive:

```
  'azure' => [
            'driver'    => 'azure',
            'name'      => env('AZURE_STORAGE_NAME'),
            'key'       => env('AZURE_STORAGE_KEY'),
            'container' => env('AZURE_STORAGE_CONTAINER'),
            'url'       => env('AZURE_STORAGE_URL'),
            'prefix'    => null,
        ],
```

I've tried: double/single quotes, removing the '==', switching the keys. I am using the key from 'Access Keys' inside Azure Any ideas on that? pls help

**Comment by matthewbdaly** [comment]
This issue is thrown in https://github.com/Azure/azure-storage-common-php/blob/fe85677aa5188f8efe6916b4d6773a194e2c2ede/src/Common/Internal/Resources.php so I doubt it's anything to do with this package.

You might try instantiating Flysystem manually using these credentials rather than using the Laravel integration, as if it still occurs under those circumstances it will rule out any issue with this package.
