### ISSUE TITLE
Support AAD authentication

### ISSUE THREAD

**Issue by ADRDev** [matthewbdaly/laravel-azure-storage#39]
Could support be added for AAD authentication method as mentioned in the azure storage php repo? https://github.com/Azure/azure-storage-php/

It appears very similar to SAS method but passing account name instead of saskey.

**Comment by matthewbdaly** [comment]
I don't see any reason why not, but I think the critical thing is probably whether it's possible to do it with Flysystem's Azure driver, since this package is just a wrapper for that so it can be used with the Laravel storage API.

I don't have the bandwidth to work on it, but I'd be happy to consider any pull request.
