### ISSUE TITLE
New feature requesting for removed file from Azure Storage

### ISSUE THREAD

**Issue by imrjat** [matthewbdaly/laravel-azure-storage#40]
**[matthewbdaly/laravel-azure-storage](https://github.com/matthewbdaly/laravel-azure-storage) package working great while uploading file to Azure Storage but I'm not able to removing file from Azure Storage**

Because this project has no functionality for removing file yet:

**Is your feature request related to a problem? Please describe.**
We are shifting lots of project from AWS to Azure. Now we are facing issue like removing files

**Describe the solution you'd like**
`function remove_file_azure($file){
    return Storage::disk('azure')->delete($file);
}`

**Additional context**
 ![Screenshot from 2021-06-18 09-16-36](https://user-images.githubusercontent.com/39850508/122503350-e6ccbc80-d015-11eb-96dc-cf5d2c7634fb.png) .

Thankyou so much

**Comment by matthewbdaly** [comment]
I don't understand the problem you have here. This package is just a thin wrapper for Flysystem's Azure driver to make it work with Laravel's storage API, and that has the `delete()` method you're using above, which will do that.

If the problem is that that doesn't work, then it's unlikely this package is anything to do with that since it doesn't touch that functionality. It's far more likely any issue is in either the Flysystem Azure driver or the PHP SDK it wraps.
