### ISSUE TITLE
Setting CacheControl headers for uploaded files

### ISSUE THREAD

**Issue by apsg** [matthewbdaly/laravel-azure-storage#59]
Hello, 

It would be great to set CacheControl headers on uploads just as it is done in S3. I tried adding options to disk definition in `filesystems.php` but with no luck:

![image](https://user-images.githubusercontent.com/3952574/221360944-42e76e88-e8c7-495a-a9fa-638697371f66.png)

**Comment by matthewbdaly** [comment]
Sorry, but I don't think this is likely to be possible through this package, not to mention _way_ outside the scope of it.

This package is basically just a wrapper for the Flysystem Azure Blob Storage integration, and that doesn't implement any kind of cache control, so there's nothing I can do via that.

It does, however, resolve `MicrosoftAzure\Storage\Blob\BlobRestProxy` through the container, so it _may_ be you can customise how that is resolved in your application in order to do that. However, finding the means to do that will require a lot of digging, and I simply haven't had the need for this package in a while, nor do I have an account I can use to hand as I haven't used Azure for several years now, so I'm not in a position to be able to do so.
